name: Run Docker Compose

on:
  push:
    branches: [ master ]

jobs:
  run-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start Compose services
      run: |
        docker compose up -d

    - name: Copy generated file from container
      run: |
        docker cp krakend:/etc/krakend/out.json .

    - name: Upload asset
      uses: actions/upload-artifact@v2
      with:
        name: out.json
        path: out.json

